
export const currencies = [
    "Orb of Alteration",
    "Orb of Fusing",
    "Orb of Alchemy",
    "Chaos Orb",
    "Gemcutter's Prism",
    "Exalted Orb",
    "Chromatic Orb",
    "Jeweller's Orb",
    "Engineer's Orb",
    "Infused Engineer's Orb",
    "Orb of Chance",
    "Cartographer's Chisel",
    "Orb of Scouring",
    "Blessed Orb",
    "Orb of Regret",
    "Regal Orb",
    "Divine Orb",
    "Vaal Orb",
    "Orb of Annulment",
    "Orb of Binding",
    "Ancient Orb",
    "Orb of Horizons",
    "Harbinger's Orb",
    "Scroll of Wisdom",
    "Portal Scroll",
    "Armourer's Scrap",
    "Blacksmith's Whetstone",
    "Glassblower's Bauble",
    "Orb of Transmutation",
    "Orb of Augmentation",
    "Mirror of Kalandra",
    "Eternal Orb",
    "Perandus Coin",
    "Rogue's Marker",
    "Silver Coin",
    "Crusader's Exalted Orb",
    "Redeemer's Exalted Orb",
    "Hunter's Exalted Orb",
    "Warlord's Exalted Orb",
    "Awakener's Orb",
    "Maven's Orb",
    "Facetor's Lens",
    "Prime Regrading Lens",
    "Secondary Regrading Lens",
    "Tempering Orb",
    "Tailoring Orb",
    "Stacked Deck",
    "Ritual Vessel",
    "Simple Sextant",
    "Prime Sextant",
    "Awakened Sextant",
    "Elevated Sextant",
    "Orb of Unmaking",
    "Blessing of Xoph",
    "Blessing of Tul",
    "Blessing of Esh",
    "Blessing of Uul-Netol",
    "Blessing of Chayula",
]